version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: webpack
    versions:
    - 5.22.0
    - 5.23.0
    - 5.24.0
    - 5.24.1
    - 5.24.2
    - 5.34.0
  - dependency-name: eslint-config-prettier
    versions:
    - 8.0.0
    - 8.1.0
    - 8.2.0
  - dependency-name: "@testing-library/user-event"
    versions:
    - 13.0.0
    - 13.0.1
    - 13.0.10
    - 13.0.2
    - 13.0.6
    - 13.0.7
  - dependency-name: husky
    versions:
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
  - dependency-name: html-webpack-plugin
    versions:
    - 5.0.0
    - 5.1.0
