# Default
[build]
  publish = ".dist"
  command = "node ./scripts/netlifyEnv.js && yarn build"

# Asset Optimization
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = false
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true

# API
[[redirects]]
  from    = "/api/*"
  to      = "API_REDIRECT"
  status  = 200

# SPA
[[redirects]]
  from    = "/*"
  to      = "/index.html"
  status  = 200
