# Global settings applied to the whole site.
# “base” is directory to change to before starting build, and
# “publish” is the directory to publish (relative to root of your repo).
# “command” is your build command.

[build]
  base    = ""
  publish = ".dist"
  command = "NODE_ENV=development yarn build"

# Production context: All deploys to the main
# repository branch will inherit these settings.
[context.production]
  command = "NODE_ENV=production yarn build"

# Branch Deploy context: All deploys that are not in
# an active Deploy Preview will inherit these settings.
[context.branch-deploy]
  command = "NODE_ENV=staging yarn build"

# API
[[redirects]]
  from    = "/api/*"
  to      = "http://path.to.api.com/api/:splat"
  status  = 200

# Always redirect any request to our index.html
# and return the status code 200.
[[redirects]]
  from    = "/*"
  to      = "/index.html"
  status  = 200
