# Default
[build]
  publish = ".dist"
  command = "node ./scripts/netlifyEnv.js && yarn build"

# Asset Optimization
[build.processing]
  skip_processing = true
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = false
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true

# Production
[context.production.environment]
  API_LOCATION = "https://path.to.production.api.com/production/api/:splat"

# Staging
[context.staging.environment]
  API_LOCATION = "https://path.to.staging.api.com/staging/api/:splat"

# API
[[redirects]]
  from    = "/api/*"
  to      = "API_REDIRECT"
  status  = 200

# SPA
[[redirects]]
  from    = "/*"
  to      = "/index.html"
  status  = 200
