version: 2
jobs:
  lint:
    docker:
      - image: circleci/node:14.15
    steps:
      - checkout
      - run: yarn install
      - run: yarn lint
  test:
    docker:
      - image: circleci/node:14.15
    steps:
      - checkout
      - run: yarn install
      - run: yarn test
  build:
    docker:
      - image: circleci/node:14.15
    steps:
      - checkout
      - run: yarn install
      - run: yarn build
workflows:
  version: 2
  build_and_test:
    jobs:
      - lint
      - test
      - build
