name: FE Template CI
on: push

jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: '14.15.4'
        cache: 'yarn'
    - run: yarn install
    - run: yarn lint
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: '14.15.4'
        cache: 'yarn'
    - run: yarn install
    - run: yarn test
  build:
    name: Build application
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: '14.15.4'
        cache: 'yarn'
    - run: yarn install
    - run: yarn build
